//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamTran
    {
        public int ETID { get; set; }
        public Nullable<int> EID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SubID { get; set; }
        public Nullable<int> StdID { get; set; }
        public Nullable<int> ACID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Timing { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<decimal> PassingMarks { get; set; }
    }
}
