//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountingYear> AccountingYears { get; set; }
        public DbSet<ModuleMaster> ModuleMasters { get; set; }
        public DbSet<RoleMaster> RoleMasters { get; set; }
        public DbSet<UserFormTran> UserFormTrans { get; set; }
        public DbSet<UserModuleTran> UserModuleTrans { get; set; }
        public DbSet<CityMaster> CityMasters { get; set; }
        public DbSet<DistrictMaster> DistrictMasters { get; set; }
        public DbSet<StandardMaster> StandardMasters { get; set; }
        public DbSet<StudentMaster> StudentMasters { get; set; }
        public DbSet<SubjectMaster> SubjectMasters { get; set; }
        public DbSet<ZoneMaster> ZoneMasters { get; set; }
        public DbSet<FormMaster> FormMasters { get; set; }
        public DbSet<QRCodeMaster> QRCodeMasters { get; set; }
        public DbSet<SubTran> SubTrans { get; set; }
        public DbSet<UserDistrictTran> UserDistrictTrans { get; set; }
        public DbSet<ExamTran> ExamTrans { get; set; }
        public DbSet<ResultMaster> ResultMasters { get; set; }
        public DbSet<ExamMaster> ExamMasters { get; set; }
        public DbSet<SchoolMaster> SchoolMasters { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
    }
}
