//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        public int MID { get; set; }
        public string Module { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string Sequence { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
