//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCodeMaster
    {
        public int QRID { get; set; }
        public Nullable<int> ETID { get; set; }
        public Nullable<int> StudID { get; set; }
        public Nullable<int> SubID { get; set; }
        public byte[] QRCodeImage { get; set; }
        public string QRCode { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> EID { get; set; }
        public Nullable<int> StdID { get; set; }
    }
}
