//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMaster
    {
        public int SchoolID { get; set; }
        public Nullable<int> DID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> ZID { get; set; }
        public string Name { get; set; }
        public string CenterCode { get; set; }
        public string Prefix { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Principal { get; set; }
        public string VicePrincipal { get; set; }
        public string Website { get; set; }
        public string Logo { get; set; }
        public string Sign { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
