//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMaster
    {
        public int StudID { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> DID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> ZID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> StdID { get; set; }
        public Nullable<int> ACID { get; set; }
        public string FormNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string RollNo { get; set; }
        public string Photo { get; set; }
        public string Sign { get; set; }
        public string Thumb { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
