//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTran
    {
        public int STID { get; set; }
        public Nullable<int> StudID { get; set; }
        public Nullable<int> SubID { get; set; }
        public bool IsChecked { get; set; }
    }
}
